/*
 * UpdateDialog.java
 *
 * Created on October 22, 2008, 1:41 PM
 */

package tmarker;

import edu.stanford.ejalbert.BrowserLauncher;
import edu.stanford.ejalbert.exception.BrowserLaunchingInitializingException;
import edu.stanford.ejalbert.exception.UnsupportedOperatingSystemException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * The Window that pops up if the user choses to update TMARKER.
 * @author Peter Schueffler
 */
public class UpdateDialog extends javax.swing.JDialog {
    
    boolean isOutOfDate = false;
    
    /**
     * Opens a new UpdateDialog and sets the text an buttons according to the current revision of the program.
     * @param parent The parent frame for this dialog box.
     * @param thisRevision The current local revision (version) of this program.
     * @param remoteRevision The remote revision (version) of the program.
     * @param modal True, if this dialog should be modal.
     */
    private UpdateDialog(JFrame parent, String thisRevision, String remoteRevision, boolean modal) {
        super(parent, modal);
        initComponents();
        setButtons(thisRevision, remoteRevision);
    }
    
    /**
     * Sets the Buttons and writes the text according to the versions that are locally and remotely available.
     * @param thisRevision The local version of TMARKER.
     * @param remoteRevision The remote version of TMARKER.
     */
    private void setButtons(String thisRevision, String remoteRevision) {
        int thisRevisionInt = Integer.parseInt(thisRevision.replaceAll("\\.", "").replaceAll("'", ""));
        int remoteRevisionInt = Integer.parseInt(remoteRevision.replaceAll("\\.", "").replaceAll("'", ""));
        boolean connectionFailure = remoteRevisionInt < 0;
        isOutOfDate = remoteRevisionInt > thisRevisionInt;
        if (connectionFailure) {
            jLabel4.setText("");
            jLabel5.setText("");
        }
        else {
            jLabel4.setText("Local Version: TMARKER v" + thisRevision);
            jLabel5.setText("Online Version: TMARKER v" + remoteRevision);
        }
        jLabel1.setVisible(!connectionFailure && !isOutOfDate);
        jLabel2.setVisible(!connectionFailure && isOutOfDate);
        jButton1.setVisible(!connectionFailure && isOutOfDate);
        jLabel3.setVisible(connectionFailure);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TMARKER Update Check");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("You are using the latest version of TMARKER. Enjoy!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("A new TMARKER version is available. Please load the latest version.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        getContentPane().add(jLabel2, gridBagConstraints);

        jButton1.setText("Go to TMARKER Download");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel3.setText("Update check failed.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            BrowserLauncher bl = new BrowserLauncher();
            bl.openURLinBrowser("http://www.nexus.ethz.ch");
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.INFO, "Trying to open http://www.nexus.ethz.ch/#page=Home");
        } catch (BrowserLaunchingInitializingException ex) {
            Logger.getLogger(UpdateDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedOperatingSystemException ex) {
            Logger.getLogger(UpdateDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Opens a new UpdateDialog and sets the text an buttons according to the current revision of the program.
     * @param parent The parent frame for this dialog box.
     * @param thisRevision The current local revision (version) of this program.
     * @param remoteRevision The remote revision (version) of the program.
     * @param verbose If true, the result will be displayed in any case. If false
     * the result will be displayed only if this TMARKER version is out of date.
     */
    public static void main(final JFrame parent, final String thisRevision, final String remoteRevision, final boolean verbose) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final UpdateDialog dialog = new UpdateDialog(parent, thisRevision, remoteRevision, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.pack();
                dialog.setLocationRelativeTo(parent);
                if (verbose || dialog.isOutOfDate) {
                    dialog.setVisible(true);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    
}
